# This is a sample build configuration for Ruby.
# Check our guides at https://confluence.atlassian.com/x/8r-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ruby:2.4.0

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - ruby -c 
          - gem install test-kitchen
          - gem install kitchen-docker -v 2.3.0
          - gem install chef -v 13.0.118
          - chef exec rspec 